services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: skripsi-ridho:latest
    container_name: skripsi_ridho
    restart: unless-stopped
    ports:
      - '9003:80'
    env_file:
      - .env
    volumes:
      - ./.env:/var/www/html/.env
    networks:
      - jobless

networks:
  jobless:
    external: true
